const data = [
  {
    id: 1,
    name_homestay: 'Island Bliss Resort',
    image: null,
    rating: 4.95,
    location: 'Anyer Serang',
    price: '$580',
  },
  {
    id: 2,
    name_homestay: 'Luxo Suites Hotel',
    image: null,
    rating: 4.8,
    location: 'Kota Serang',
    price: '$380',
  },
  {
    id: 3,
    name_homestay: 'Backpackers Hostel',
    image: null,
    rating: 4.98,
    location: 'Anyer Serang',
    price: '$1880',
  },
  {
    id: 4,
    name_homestay: "Nature's Campsite",
    image: null,
    rating: 4.73,
    location: 'Sleman,Yogyakarta',
    price: '$1980',
  },
  {
    id: 5,
    name_homestay: 'Royal Oasis Resort',
    image: null,
    rating: 4.81,
    location: 'Kuta, Bali',
    price: '$2080',
  },
  {
    id: 6,
    name_homestay: 'Treehouse Escapes',
    image: null,
    rating: 5,
    location: 'Bandung, Jawa Barat',
    price: '$3000',
  },
  {
    id: 7,
    name_homestay: 'The Edge Apartment',
    image: null,
    rating: 4.2,
    location: 'Cimahi, Jawa Barat',
    price: '$400',
  },
];

export default data;
